### ISSUE TITLE
Sidebar HE

### ISSUE THREAD

**Issue by AlexKuehnSB12** [Niko-Becker-B12/B12-Showroom-System-Documentation#11]
Buttons könnten einklappbar sein um mehr Übersicht zu bieten.

![image](https://user-images.githubusercontent.com/93521824/182607272-f853f9cf-c494-46a6-bcc3-8222889724ad.png)

**Comment by Niko-Becker-B12** [comment]
![grafik](https://user-images.githubusercontent.com/79908681/183852810-d2e8bf8d-f26e-4d54-8a50-360c2a9db4d4.png)
