### ISSUE TITLE
Sidebar buttons reset

### ISSUE THREAD

**Issue by AlexKuehnSB12** [Niko-Becker-B12/B12-Showroom-System-Documentation#12]
Sidebar buttons have the ability to reset themselves. But there is no way to trigger it.

**Comment by Niko-Becker-B12** [comment]
`CodeNameDockingElements.ResetSidebarButton(int index)` 
This will reset all Sidebar-Head-Buttons, except the given index.
If the Index = -1 all Sidebar-Head-Buttons will be reset.
`CodeNameDockingElements.ResetSidebarButtonSubButtons(int index)` 
This will reset the Sidebar-Sub-Buttons of a given Head-Button.
